{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.jaro-jaro",
    "module": "compose-dialog",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-dialog-1.0.4.aar",
          "url": "compose-dialog-1.0.4.aar",
          "size": 34179,
          "sha512": "681c80c678555528a7d00d8dfd7fba98561e5d8c1e81277c8f06c808428e89b656f6a9ba6afc33b65984c878e880c325a3659cccb1159fd5824d145733b662d4",
          "sha256": "cf751c8bd3fcdfd19f0cd76d1fa25b8f39504e9228cbb9d26c918d383d0f77ed",
          "sha1": "d75231ff33d797a221e590aa171e187ecf1d3b77",
          "md5": "8bbe1af74bb04b04052e0fe10cfd6fd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-dialog-1.0.4.aar",
          "url": "compose-dialog-1.0.4.aar",
          "size": 34179,
          "sha512": "681c80c678555528a7d00d8dfd7fba98561e5d8c1e81277c8f06c808428e89b656f6a9ba6afc33b65984c878e880c325a3659cccb1159fd5824d145733b662d4",
          "sha256": "cf751c8bd3fcdfd19f0cd76d1fa25b8f39504e9228cbb9d26c918d383d0f77ed",
          "sha1": "d75231ff33d797a221e590aa171e187ecf1d3b77",
          "md5": "8bbe1af74bb04b04052e0fe10cfd6fd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-dialog-1.0.4-sources.jar",
          "url": "compose-dialog-1.0.4-sources.jar",
          "size": 1816,
          "sha512": "09a8e617e9fe9b27e39977b0011fd6d76574bdc01f856d21861503fd83043d534f6916c1b9bdf56ef1e786c76fd9be18b079323d8bb80541cd9054a1378d3ae6",
          "sha256": "72ebb130a8634fb0db0507b2bfd795dfce0e67c6eeef651d20fedc004bfb64c5",
          "sha1": "8c22ae89f2850f7f2c39c18b6d8cbd5b80a5f911",
          "md5": "63f44f248ae784c44602023a3fb95ca2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-dialog-1.0.4-javadoc.jar",
          "url": "compose-dialog-1.0.4-javadoc.jar",
          "size": 282436,
          "sha512": "dff0dcbc7f0613c68822cab6371e4e1eecdc17a159c23cd30c4480712b7ba9fb04f7819744de14fa4115ba49b6bf496c8846b4ade79036a62c76ec3e325cdbb7",
          "sha256": "e35b9e47d905de7cb869a5b9a3484338bd780cba01f1c9067ec5cceff79713d3",
          "sha1": "98e1b852cafc8433a5ef752a2517364871ebf80b",
          "md5": "ef7a2af0129c11f7737726d7e3185e6c"
        }
      ]
    },
    {
      "name": "releaseTestFixturesVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.jaro-jaro",
          "module": "compose-dialog",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "compose-dialog-1.0.4-test-fixtures.aar",
          "url": "compose-dialog-1.0.4-test-fixtures.aar",
          "size": 792,
          "sha512": "4c7df48638f7118c64efc740051eeb0ac39e8f89277160a40354ce69a58d648aa61c1801d9fe6b993069d8fcf8ae1d652043cf49cba519097982f533a5e9d121",
          "sha256": "691a546ecdbdbabbebe6afc91a3ab3ea621a756772b7ec9b096ca7e5eab97f83",
          "sha1": "fdb58d11c27cd4f4655a604586fe18b2b67534b3",
          "md5": "f61f68146af8adce8f2c8123987f4aab"
        }
      ],
      "capabilities": [
        {
          "group": "compose-dialog",
          "name": "compose-dialog-test-fixtures",
          "version": "unspecified"
        }
      ]
    },
    {
      "name": "releaseTestFixturesVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.jaro-jaro",
          "module": "compose-dialog",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "compose-dialog-1.0.4-test-fixtures.aar",
          "url": "compose-dialog-1.0.4-test-fixtures.aar",
          "size": 792,
          "sha512": "4c7df48638f7118c64efc740051eeb0ac39e8f89277160a40354ce69a58d648aa61c1801d9fe6b993069d8fcf8ae1d652043cf49cba519097982f533a5e9d121",
          "sha256": "691a546ecdbdbabbebe6afc91a3ab3ea621a756772b7ec9b096ca7e5eab97f83",
          "sha1": "fdb58d11c27cd4f4655a604586fe18b2b67534b3",
          "md5": "f61f68146af8adce8f2c8123987f4aab"
        }
      ],
      "capabilities": [
        {
          "group": "compose-dialog",
          "name": "compose-dialog-test-fixtures",
          "version": "unspecified"
        }
      ]
    }
  ]
}
